[package]
name = "job2event"
version = "1.2.4"
edition = "2021"

[dependencies]
calamine = "0.26.1"
chrono = "0.4.39"
webbrowser = "1.0.3"
actix-web = "4.9.0"
actix-files = "0.6.6"
serde = { version = "1.0.215", features = ["derive"] }
tokio = "1.42.0"
sysinfo = "0.33.0"