[package]
name = "job2event"
version = "1.2.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
chrono = "0.4.38"
webbrowser = "1.0.3"

actix-web = "4.9.0"
actix-files = "0.6"
tokio = "1.0"

serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0"